const script = [
  {
    tagName: "<!--...-->",
    tagDescription:
      "This is how you comment in HTML. Comments are useful in development when testing where you can disable line of codes or information when yopu work in teams.",
    tagExample: "<!-- this is a comment -->",
  },
  {
    tagName: "<!DOCTYPE>",
    tagDescription:
      "this is the declaraction that goes at the beginning of the page, it is a MUST and without this you can not work.",
    tagExample: "<!DOCTYPE html>",
  },
  {
    tagName: "<a>",
    tagDescription:
      "This is the anchor tag. You can create hyperlinks alongside the href tag",
    tagExample: "<a href='http://localhost:3000'>",
  },
  {
    tagName: "<abbr>",
    tagDescription:
      "Abbreviation tag, it is useful for creating acronyms for long names, and hovering over with the mouse reveals the full name.",
    tagExample:
      "The <abbr title='Ultimate Fighting Championship'>UFC</abbr> was founded in 1948.",
  },
  {
    tagName: "<acronym>",
    tagDescription: "see <abbr>.",
    tagExample: "not supported",
  },
  {
    tagName: "<address>",
    tagDescription:
      "The address tag defines the address of a person, the email it is rendered in italics and breaks are added at the begginning and end of the address tag.",
    tagExample:
      "<p>Contact:</p><address><a href='mailto:strawberry@fruit.com'>strawberry@fruit.com</a><br><a href='phone:+23789231232'>23789231232</a></address>",
  },
  {
    tagName: "<applet>",
    tagDescription:
      "This was made for plugins like Flash, modern browsers have stopped this.",
    tagExample: "not supported",
  },
  {
    tagName: "<area>",
    tagDescription:
      "This tag can make an area that is clickable for example images. This tag support different shapes with the Shape attribute you can make it rectangle, circle or poligonal regions.",
    tagExample: "<area shape='default | rect | circle | poly'>",
  },
  {
    tagName: "<article>",
    tagDescription: "Article is part of HTML semantics ",
    tagExample: "NULL",
  },
  { tagName: "<aside>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<audio>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<b>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<base>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<basefont>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<bdi>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<bdo>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<big>", tagDescription: "NULL", tagExample: "NULL" },
  {
    tagName: "<blockquote>",
    tagDescription: "NULL",
    tagExample: "NULL",
  },
  { tagName: "<body>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<br>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<button>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<canvas>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<caption>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<center>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<cite>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<code>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<col>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<colgroup>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<data>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<datalist>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<dd>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<del>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<details>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<dfn>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<dialog>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<dir>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<div>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<dt>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<em>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<embed>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<fieldset>", tagDescription: "NULL", tagExample: "NULL" },
  {
    tagName: "<figcaption>",
    tagDescription: "NULL",
    tagExample: "NULL",
  },
  { tagName: "<figure>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<font>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<footer>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<form>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<frame>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<frameset>", tagDescription: "NULL", tagExample: "NULL" },
  {
    tagName: "<h1> ... <h6>",
    tagDescription: "NULL",
    tagExample: "NULL",
  },
  { tagName: "<head>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<header>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<hr>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<html>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<i>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<iframe>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<img>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<input>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<ins>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<kbd>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<label>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<legend>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<li>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<link>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<main>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<map>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<mark>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<meta>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<meter>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<nav>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<noframes>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<noscript>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<object>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<ol>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<optgroup>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<option>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<output>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<p>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<param>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<picture>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<pre>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<progress>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<q>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<rp>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<rt>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<ruby>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<s>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<samp>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<script>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<section>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<select>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<small>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<source>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<span>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<strike>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<strong>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<style>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<sub>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<summary>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<sup>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<svg>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<table>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<tbody>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<td>", tagDescription: "NULL", tagExample: "NULL" },
  {
    tagName: "<template>",
    tagDescription: "NULL",
    tagExample: "NULL",
  },
  {
    tagName: "<textarea>",
    tagDescription: "NULL",
    tagExample: "NULL",
  },
  { tagName: "<tfoot>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<th>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<thead>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<time>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<title>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<tr>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<track>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<tt>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<u>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<ul>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<var>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<video>", tagDescription: "NULL", tagExample: "NULL" },
  { tagName: "<wbr>", tagDescription: "NULL", tagExample: "NULL" },
];

module.exports = script;
